locale: "zh-CN"
title: "Zepp's site"
description: "Zepp is a boring boy longing for a true friend"
url: "https://zepplu.github.io"
baseurl: "/"

skin: "/assets/css/skins/light.css"
data_format: "%Y/%m/%d, %H:%M:%S"
#read_time: true
#words_per_minute: 200
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

google_fonts:
    - name: "Noto Sans SC"
      weights: "400,700"
    - name: "Noto Serif SC"
      weights: "400,700"
    - name: "Noto Sans TC"
      weights: "400,700"
    - name: "Noto Serif TC"
      weights: "400,700"
    - name: "Source Code Pro"
      weights: "400,400i,700,700i"

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate
